# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import event_email.utils


class Migration(migrations.Migration):

    dependencies = [
        ('event_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='source',
            field=models.FileField(blank=True, upload_to=event_email.utils.event_email_directory_path),
        ),
    ]
