# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_email', '0002_auto_20170828_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='html',
            field=models.CharField(default='', max_length=2000, verbose_name='HTML'),
            preserve_default=False,
        ),
    ]
