# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_email', '0005_auto_20170919_1102'),
        ('event_email', '0005_auto_20170919_1601'),
    ]

    operations = [
    ]
