# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_email', '0006_schedule_user'),
        ('event_email', '0006_merge_20171029_1349'),
    ]

    operations = [
    ]
