# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import geoposition.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('Created', 'Created'), ('Sent', 'Sent'), ('Opened', 'Opened'), ('Clicked', 'Clicked')], default='Created', max_length=100, no_check_for_status=True, verbose_name='Email status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('sent_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='Email sent at', when=set(['Sent']))),
                ('opened_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='Email opened at', when=set(['Opened']))),
                ('clicked_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='Email clicked at', when=set(['Clicked']))),
                ('token', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source', models.FileField(upload_to='event_email')),
                ('template_name', models.CharField(max_length=50, unique=True, verbose_name='Name of template')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email_address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('token', models.CharField(max_length=50)),
                ('subscribe', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sending_frequency', model_utils.fields.StatusField(choices=[('One time', 'One time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='One time', max_length=100, no_check_for_status=True, verbose_name='Frequency of sending')),
                ('complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_email.EmailTemplate', verbose_name='EmailTemplate')),
                ('recipients', models.ManyToManyField(to='event_email.Recipient', verbose_name='Recipients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='email',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_email.Event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='email',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_email.Recipient', verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='email',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_email.Schedule', verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='email',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_email.EmailTemplate', verbose_name='Email Template'),
        ),
        migrations.AddField(
            model_name='email',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_email', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
