# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_email', '0004_emailtemplate_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='source',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='text',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Text'),
        ),
    ]
