# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        regex="^Event/~create/$",
        view=views.EventCreateView.as_view(),
        name='Event_create',
    ),
    url(
        regex="^Event/(?P<pk>\d+)/~delete/$",
        view=views.EventDeleteView.as_view(),
        name='Event_delete',
    ),
    url(
        regex="^Event/(?P<pk>\d+)/$",
        view=views.EventDetailView.as_view(),
        name='Event_detail',
    ),
    url(
        regex="^Event/(?P<pk>\d+)/~update/$",
        view=views.EventUpdateView.as_view(),
        name='Event_update',
    ),
    url(
        regex="^Event/$",
        view=views.EventListView.as_view(),
        name='Event_list',
    ),
    url(
        regex="^Email/~create/$",
        view=views.EmailCreateView.as_view(),
        name='Email_create',
    ),
    url(
        regex="^Email/(?P<pk>\d+)/~delete/$",
        view=views.EmailDeleteView.as_view(),
        name='Email_delete',
    ),
    url(
        regex="^Email/(?P<pk>\d+)/$",
        view=views.EmailDetailView.as_view(),
        name='Email_detail',
    ),
    url(
        regex="^Email/(?P<pk>\d+)/~update/$",
        view=views.EmailUpdateView.as_view(),
        name='Email_update',
    ),
    url(
        regex="^Email/$",
        view=views.EmailListView.as_view(),
        name='Email_list',
    ),
	url(
        regex="^EmailTemplate/~create/$",
        view=views.EmailTemplateCreateView.as_view(),
        name='EmailTemplate_create',
    ),
    url(
        regex="^EmailTemplate/(?P<pk>\d+)/~delete/$",
        view=views.EmailTemplateDeleteView.as_view(),
        name='EmailTemplate_delete',
    ),
    url(
        regex="^EmailTemplate/(?P<pk>\d+)/$",
        view=views.EmailTemplateDetailView.as_view(),
        name='EmailTemplate_detail',
    ),
    url(
        regex="^EmailTemplate/(?P<pk>\d+)/~update/$",
        view=views.EmailTemplateUpdateView.as_view(),
        name='EmailTemplate_update',
    ),
    url(
        regex="^EmailTemplate/$",
        view=views.EmailTemplateListView.as_view(),
        name='EmailTemplate_list',
    ),
    url(
        regex="^Schedule/~create/$",
        view=views.ScheduleCreateView.as_view(),
        name='Schedule_create',
    ),
    url(
        regex="^Schedule/(?P<pk>\d+)/~delete/$",
        view=views.ScheduleDeleteView.as_view(),
        name='Schedule_delete',
    ),
    url(
        regex="^Schedule/(?P<pk>\d+)/$",
        view=views.ScheduleDetailView.as_view(),
        name='Schedule_detail',
    ),
    url(
        regex="^Schedule/(?P<pk>\d+)/~update/$",
        view=views.ScheduleUpdateView.as_view(),
        name='Schedule_update',
    ),
    url(
        regex="^Schedule/$",
        view=views.ScheduleListView.as_view(),
        name='Schedule_list',
    ),
    url(
        regex="^Recipient/~create/$",
        view=views.RecipientCreateView.as_view(),
        name='Recipient_create',
    ),
    url(
        regex="^Recipient/(?P<pk>\d+)/~delete/$",
        view=views.RecipientDeleteView.as_view(),
        name='Recipient_delete',
    ),
    url(
        regex="^Recipient/(?P<pk>\d+)/$",
        view=views.RecipientDetailView.as_view(),
        name='Recipient_detail',
    ),
    url(
        regex="^Recipient/(?P<pk>\d+)/~update/$",
        view=views.RecipientUpdateView.as_view(),
        name='Recipient_update',
    ),
    url(
        regex="^Recipient/$",
        view=views.RecipientListView.as_view(),
        name='Recipient_list',
    ),
    url(
        regex="^Recipient/(?P<token>\d+)/~subscribe/$",
        view=views.RecipientSubscribeView.as_view(),
        name='Recipient_subscribe',
    ),
    url(
        regex="^Recipient/(?P<token>\d+)/~unsubscribe/$",
        view=views.RecipientUnsubscribeView.as_view(),
        name='Recipient_unsubscribe',
    ),
	 url(
        regex="^(?P<tracking_pixel>.*?).png", 
        view=views.tracking_pixel, 
        name='tracking_pixel'
    ),
    
    ]